### ISSUE TITLE
Namespaces when deserilizing 

### ISSUE THREAD

**Issue by aeromac** [treblereel/mapper-xml#110]
I'm trying to deserialize Word Docx XML, which has the namespace of "w" <w:document>, <w:body> etc, but not having much luck.
@XmlSchema values set in package-info.java seem to be used in the generated serializers but not the deserializers or mappers. Could this be the issue?

**Comment by aeromac** [comment]
Sorry, my bad - the issue I had was unrelated to namespaces (using XmlElements instead of XmlElementRefs). Although the generated deserializer code doesn't contain the namespace, it deserializes fine

**Comment by treblereel** [comment]
@aeromac In case you have any issues, just ping me
