### ISSUE TITLE
XmlValue doesn't support XmlCData annotation

### ISSUE THREAD

**Issue by hasys** [treblereel/mapper-xml#99]
If you have a XmlValue annotation on the field, it's content correctly converted as XML Element value, but if you add XmlCData, it will be ignored.

Example:

```java
public class User {
         @XmlValue
         @XmlCData
         public String name;
     }
``` 

Will produce:
```xml
<?xml version='1.0' encoding='UTF-8'?><User>testName</User>
```

But expected:
```xml
<?xml version='1.0' encoding='UTF-8'?><User><![CDATA[testName]]></User>
```

**Comment by hasys** [comment]
Hi @treblereel, can't edit assignee here, so just pinging you in comments. Thank you!

**Comment by treblereel** [comment]
@hasys good catch, thanks, i ll fix it asap

**Comment by treblereel** [comment]
@hasys for now your case can be fixed by setting @XmlCData(value = false) like here:
https://github.com/treblereel/mapper-xml/blob/8be3d4a79cec81d89845bbfaa9f38a2ffc9d8145/tests/jre/src/test/java/org/treblereel/gwt/xml/mapper/client/tests/annotations/cdata/Value.java#L29

**Comment by hasys** [comment]
@hasys for now your case can be fixed by setting @XmlCData(value = false) like here:
https://github.com/treblereel/mapper-xml/blob/8be3d4a79cec81d89845bbfaa9f38a2ffc9d8145/tests/jre/src/test/java/org/treblereel/gwt/xml/mapper/client/tests/annotations/cdata/Value.java#L29

_Originally posted by @treblereel in https://github.com/treblereel/mapper-xml/issues/99#issuecomment-988270204_

CDATA didn't appear :(

**Comment by treblereel** [comment]
@hasys ok, i hope https://github.com/treblereel/mapper-xml/commit/0d2c8981a84f6c288901a6771a8777da70a2e921 fixed your issue
